version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - db_network
    restart: always
  koa-app:
    container_name: foodgo-app
    build: .
    image: anjeonghoo/food_go
    environment:
      - SPRING_DATASOURCE_USERNAME=foodgodatabase
      - SPRING_DATASOURCE_PASSWORD=foodgodatabase
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - redis
    networks:
      - db_network
networks:
  db_network:
    driver: bridge
