spring:
  profiles:
    active: prod
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

---
spring:
  config:
    activate:
      on-profile: local
    import: application-prod.yml, application-redis.yml, application-s3.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import: application-prod.yml, application-redis.yml, application-s3.yml


server:
  port: 8080
