spring:
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
---
spring:
  config:
    activate:
      on-profile: local
    import: application-prod.yml, application-redis-local.yml, application-s3.yml, application-openapi-key.yml

---
spring:
  config:
    activate:
      on-profile: prod
    import: application-prod.yml, application-redis-prod.yml, application-s3.yml, application-openapi-key.yml


server:
  port: 8080
