spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  h2-console:
    settings:
      web-allow-others: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false # hibernate 로그 남길지

jwt:
  secret: "dkqorhvmekgkwlaksdltlrksdpanjfajrdmausdksehlrpTwlckawk"
  token:
    access-expiration-time: 9999999
    refresh-expiration-time: 9999999

cors:
  allowed:
    origins: "*"

logging:
  level:
    org:
      hibernate.sql: debug
